red_kite_labs_theme_engine:
    base_template: RedKiteLabsThemeEngineBundle:Frontend:base.html.twig

assetic:
    bundles: [ RedKiteLabsThemeEngineBundle ]
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar