language: php

php:
  - 5.3
  - 5.4

before_script:
  - "mysql -e 'create database alphalemon_test;'"
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script: 
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - info@redkite-labs.com
